### ISSUE TITLE
Extraneous > in output file

### ISSUE THREAD

**Issue by johndeighan** [jamen/old-gulp-pug#21]
Using gulp-pug version 3.4.1, I'm getting this as the last line of the output file:

<html>>

So, there's an extra > character. Furthermore, there isn't a line termination character (this is under Windows 10, so I'm expecting a terminating CR LF pair).

After further experimentation, the problem above is intermittent. For example, my input file is named index.pug. I created an exact copy and named it test.pug. When I ran my gulp task, the output file index.html had the extra '>', but the test.html file did not. Running several iterations of this, there were times when the index.html file did NOT have the extra '>', but usually it does.

I have no idea whether this is a problem in the pug application or just in gulp-pug.

Here is my gulp file:

```
/* gulpfile.js */
/* jshint esnext:true, node:true */

'use strict';

var gulp = require('gulp');
var pug = require('gulp-pug');
var del = require('del');

gulp.task('html', () =>
	gulp.src('src/*.html')
		.pipe(gulp.dest('dist/'))
	);

gulp.task('pug', () =>
	gulp.src('src/*.pug')
		.pipe(pug({
			pretty: true
			}))
		.pipe(gulp.dest('dist/'))
	);

gulp.task('js', () =>
	gulp.src('src/js/*.js')
		.pipe(gulp.dest('dist/'))
	);

gulp.task('img', () =>
	gulp.src('src/img/*.*')
		.pipe(gulp.dest('dist/img/'))
	);

gulp.task('css', () =>
	gulp.src('src/css/*.css')
		.pipe(gulp.dest('dist/css/'))
	);

gulp.task('clean', (cb) => del(['dist'], cb));

gulp.task('default',
	gulp.series(
		'clean',
		gulp.parallel('html','pug','js','img','css')
		)
	);

```

**Comment by johndeighan** [comment]
I guess I should have viewed the preview. The last line of the file is, in fact:

`<html>>`

**Comment by jamen** [comment]
I'm not so sure this is an error in `gulp-pug` itself since this is a light wrapper over `pug`.  Keep in mind that `pug@latest` is actually still an alpha version, so this could likely be a bug within `pug@2.0.0-alpha6` (assuming that's the version you have)...

Could you try compiling `index.pug` from a package like [`pug-cli`](https://www.npmjs.com/package/pug-cli)?  If the error persists then it is probably an issue with `pug`.

**Comment by jamen** [comment]
I'm closing this issue since me and the owner of gulp-jade decided to collaborate on the old gulp-jade package to make to make to make the API and support compatible in gulp-pug.  So these versions will be deprecated.
